# Generated by Django 4.2.5 on 2023-10-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
