# Generated by Django 4.2.5 on 2023-10-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_project'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='startdate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration_unit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='projects', to='account.user'),
        ),
    ]
