# Generated by Django 4.2.5 on 2023-10-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_list_created_at_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
