# Generated by Django 4.2.5 on 2023-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_project'),
        ('dashboard', '0002_rename_end_date_project_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='projects', to='account.user'),
        ),
    ]
