# Generated by Django 4.2.5 on 2023-10-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_activitylog_timestamp_alter_list_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Pending', max_length=12),
        ),
    ]
